var dlgs = { 
    "dlg1" : "Bonjour ceci est un essai",
    "dlg2" : '"Cela faisait longtemps que nous n’avions pas eu de visites en ces lieux."',
    "dlg3" : "Elle produisait une sorte d’écho si puissant que le bruit des vagues environnantes s’éclipsait presque." ,
    "dlg4" : '"Le poids des siècles passés est si lourd, il semblerait que vous soyez la première personne à fouler nos terres depuis plusieurs décennies."' ,
    "dlg5" : '"Quel que soit votre objectif, le cours de votre destin, et du nôtre, changera considérablement ce soir. La <b>lune</b> brille si fort."',
    "dlg6" : "Le froid ressenti auparavant vous gèle les os. Cette voix n’avait à priori aucunement l’intention de vous effrayer, mais pourtant une impression de menace subsistait dans ses paroles." ,
    "dlg7" : "Vous vous saisissez de l'une des deux torches pour vous réchauffer.", 
    "dlg8" : '" Tout invité doit être annoncé. A qui avons-nous l’honneur ?"',
    "dlg9" : '" Bienvenue en ces terres sacrées, ',
    "dlg10" :'"Nous ignorons si vous cherchez à sauver ce temple ou si le piller vous est préférable, cela ne nous intéresse pas. Mais dans un cas comme dans l’autre, il vous faudra passer par plusieurs étapes pour y entrer."',
    "dlg11" :'Vous grognez avec approbation, loin de vous l’idée de mentionner pourquoi vous êtes là, mais vous avez exploré suffisamment de vieilles ruines pour savoir que le chemin jusqu’au bout ne sera pas si facile.',
    "dlg12" : '"“Un mal ronge ce domaine et son emprise est telle que nous ne pouvons vous ouvrir la porte. Il cache nos <b>étoiles</b>. Plusieurs épreuves vous attendent pour atteindre la salle finale. Celle-ci regorge de trésors… Entre autres."',
    "dlg13" : 'Des ennemis vous attendaient donc en ces lieux. Bien, c’était noté.',
    "dlg14" : '"Apportez nous le <b>soleil</b>… Libérez nos esprits, nous vous en conjurons."',
    "dlg15" : 'La sensation de froid qui avait pris place dans votre corps disparu alors aussi vite qu’elle était apparue. Le bruit des vagues était plus vrombissant que jamais.',
    "dlg16" : 'Vous approchez la torche de la porte et vous vous apercevez alors que trois carrés ornés de symboles astraux y sont présents.',
    "dlg17" : 'Étaient-ils déjà là au début de votre échange avec la voix spectrale ? Peut être, nul n’aurait pu le deviner. Une inscription, presque illisible, est située juste en dessous des trois boutons.',
    "dlg18" : '<i>Trouvez la voie étoilée et le chemin s’ouvrira.</i>',
    "dlg19" : 'Vous vous rendez alors compte que si vous touchez les symboles ceux-ci changent. Un ordre doit être attendu. Quel est-il ?',
    "dlg20" : 'Trouvez la bonne combinaison pour poursuivre votre aventure.',
    "dlg21" : 'Les murs et les piliers environnants tremblent alors, vous avez réussi ! La porte s’ouvre en grand devant vous.',
    "dlg22" : 'Vous vous enfoncez alors dans ce qu’il semblerait être les jardins du temple, le bâtiment  ne se trouvant plus très loin.',
    "dlg23" : 'Une plainte spectrale, presque gutturale, jaillit alors des entrailles du domaine.',
    "dlg24" : '"UNE AME MAUDITE ! Malédiction, SOYEZ MAUDITS !"',
    "dlg25" : 'Il ne vous faut pas un temps de réflexion trop intense pour vous rendre compte que cette voix et celle que vous aviez entendu auparavant n’ont rien à voir entre elles.',
    "dlg26" : 'MAUDITS!!',
    "dlg27" : 'Voulez vous vous diriger vers cette nouvelle voix ?',
    "dlg28" : 'Le courage émane de vous comme un feu éternel, vous vous dirigez vers les paroles de ce qu’il s’avère être un fantôme en bien mauvaise posture. Un grand loup spectral lui fait face. ',
    "dlg29" : '"MAUDITS JE… Eh ! VOUS ! Aidez-moi !!! Ce sale cabot vient de me manger un bout de jambe, déjà que j’en ai plus beaucoup… HEH, VOUS M’ECOUTEZ ?"' ,
    "dlg30" : 'Pas trop le temps de deviner pourquoi et comment un fantôme peut manger un bout d’un autre fantôme il semblerait. Vous dégainez votre épée sans hésiter.',
    "dlg31" : 'COMBAT!!',

 }; 